login:
    type: rest
    resource: Aboutgcc\Test2Bundle\Controller\APIController

profile:
    type: rest
    resource: Aboutgcc\Test2Bundle\Controller\APIAdminController

employer:
    type: rest
    resource: Aboutgcc\Test2Bundle\Controller\APIEmployerController

employee:
    type: rest
    resource: Aboutgcc\Test2Bundle\Controller\APIEmployeeController

post-employer:
    type: rest
    resource: Aboutgcc\Test2Bundle\Controller\EmployerPostController

post-admin:
    type: rest
    resource: Aboutgcc\Test2Bundle\Controller\AdminPostController